"""
Notebook Feature Router
Persistent notes for students.
"""
from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel
from typing import List, Dict
import io
import datetime
from fpdf import FPDF

from app.features.auth.service import auth_service
from app.core.database import User
from app.core.persistence import persistence_service

router = APIRouter()

class NotesRequest(BaseModel):
    notes: str

@router.get("/")
async def get_notes(current_user: User = Depends(auth_service.get_current_user)):
    """Get notes for the current user."""
    user_id = str(current_user.id)
    notes = persistence_service.get_notes(user_id)
    return {"notes": [notes]}

@router.post("/")
async def save_notes(
    data: NotesRequest,
    current_user: User = Depends(auth_service.get_current_user)
):
    """Save notes for the current user."""
    user_id = str(current_user.id)
    persistence_service.save_notes(user_id, data.notes)
    return {"status": "success"}

@router.delete("/")
async def delete_notes(current_user: User = Depends(auth_service.get_current_user)):
    """Delete notes for the current user."""
    user_id = str(current_user.id)
    persistence_service.delete_notes(user_id)
    return {"status": "success"}

@router.get("/export")
async def export_notes_pdf(current_user: User = Depends(auth_service.get_current_user)):
    """Export notes as PDF with MSU Branding."""
    user_id = str(current_user.id)
    notes = persistence_service.get_notes(user_id)
    
    if not notes:
        raise HTTPException(status_code=400, detail="No notes to export")
        
    pdf = FPDF()
    pdf.add_page()
    
    # MSU Header
    pdf.set_font("Arial", "B", 20)
    pdf.set_text_color(24, 69, 59) # Spartan Green #18453B
    pdf.cell(0, 15, "MSU Online - Study Intelligence", ln=True, align='C')
    
    # Subtitle
    pdf.set_font("Arial", "I", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Student Notebook: {current_user.full_name}", ln=True, align='C')
    pdf.ln(10)
    
    # Horizontal line
    pdf.set_draw_color(24, 69, 59)
    pdf.line(10, 40, 200, 40)
    pdf.ln(15)
    
    # Content
    pdf.set_font("Arial", size=11)
    pdf.set_text_color(0, 0, 0)
    
    # Handle multi-line notes properly
    # Strip any potential HTML if used, for now assumes plain text or simple markdown
    clean_notes = notes.replace('\r\n', '\n')
    pdf.multi_cell(0, 8, clean_notes)
    
    # Footer
    pdf.set_y(-25)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, f"Generated by MSU Online AI Intelligence Hub on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 0, 'C')
    
    # Return as response
    pdf_bytes = pdf.output(dest="S").encode('latin-1', 'ignore')
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=MSU_Notes_{user_id}.pdf"}
    )
